### PR TITLE
updating description per file

### PR DESCRIPTION
**Pull request by kgaonkar6**
I'm adding some rough description per file in this PR. However, I'm wondering for arriba and starfusion example and tcga files I'm expecting users to use read_arriba_calls() or read_starfusion_calls() do we need to add those functions and dependencies here?

### CODE REVIEW

**Comment by federicomarini** [comment]
> do we need to add those functions and dependencies here?

While it would make sense to show this as in the full workflow, there is the issue that if we do so, we would introduce a circular dependency between the packages.
This is the main reason for the "simple" reading-in function. 
We could e.g. out the commented code showing the example of how to do it later once loaded via annoFuse

**Comment by kgaonkar6** [comment]
hmm makes sense, I just had those functions in place so the column names are always formatted the way I read them in downstream functions can you add a ticket in annoFuse repo. 

Also you mentioned this before, 1 way to reduce the size would be to make these dataframes : exonsToPlot.RDS  and pfamDataBioMart.RDS within the package since they are the major reason for the size of annoFuse. Would that be something if I work on we wouldn't need this data package? But then there will be some differences between ids we get from directly reading the gencode v27 gtf and using AnnotationDbi to get ensemble ids and genomic locations.

**Comment by federicomarini** [comment]
I'd argue that it does not hurt anyway to have the packages split up.
Two reasons: 
- thematical: it makes sense - also because we have many exemplary sets we use for showcasing the features
- technical: for Bioconductor, the size limitation is for most package quite small. For larger sets (sequencing or so), it is common to use ExperimentHub, but this is not so really what fits for our case

What would make a lot of sense though is the following:
- scripts that you used to generate exactly the versions we put as rds objects
- ... and can be used at any later time point (by us, or by any user) to generate these for the custom settings they might have (say, their newer gtf or so)

**Comment by kgaonkar6** [comment]
I've checked read.delim(...,check.names=FALSE,stringsAsFactors = F) and it seems to work fine reading the starfusion and arriba files so I think we should be good with that here?

**Review by jharenza — APPROVED** [review]

**Pull request merged**
