### PR TITLE
add v12 OPC putative oncogenic fusion file

### PR DESCRIPTION
**Pull request by jharenza**
This PR adds a new putative oncogenic file from V12 [OpenPedCan](https://github.com/PediatricOpenTargets/OpenPedCan-analysis) release.

### CODE REVIEW

**Comment by federicomarini** [comment]
I finally managed to get a good look at this.
~~Seems you only deleted some columns, but the functionality of the whole framework is basically unaltered, so I see no problem in proceeding.~~ EDIT: see below

For completeness, I would 

- [x] bump the version number? say, 0.2.0 for clarity that it is different than the older 0.1.0

- [x] do one full round of roxygenizing, maybe updating the roxygen number on top of it - I can do this so that I can fully run R CMD check on my machine with all the newest changes 😉

**Comment by federicomarini** [comment]
This removing of columns in the data package would probably still need some tests to be edited in the main package, IIRC. Cross-checking this soon!

**Review by federicomarini — APPROVED** [review]

**Review by federicomarini — CHANGES_REQUESTED** [review]
After cross-checking, some functions in the main package are actually looking and making use of the info contained in the columns.

What is the desired way of proceeding/the expected format coming up?

**Comment by jharenza** [comment]
going to close this

**Pull request closed without merging**
